export const Data = [
  {
    id: 1,
    profilePicture: "https://neal.fun/spend/images/big-mac.jpg",
    username: "Big Mac",
    price: 2,
  },
  {
    id: 2,
    profilePicture: "https://neal.fun/spend/images/flip-flops.jpg",
    username: "Flip Flops",
    price: 3,
  },
  {
    id: 3,
    profilePicture: "https://neal.fun/spend/images/coca-cola-pack.jpg",
    username: "Coca-Cola Pack",
    price: 5,
  },
  {
    id: 4,
    profilePicture: "https://neal.fun/spend/images/movie-ticket.jpg",
    username: "Movie Ticket",
    price: 12,
  },
  {
    id: 5,
    profilePicture: "https://neal.fun/spend/images/book.jpg",
    username: "Book",
    price: 15,
  },
  {
    id: 6,
    profilePicture: "https://neal.fun/spend/images/lobster-dinner.jpg",
    username: "Lobster Dinner",
    price: 45,
  },
  {
    id: 7,
    profilePicture: "https://neal.fun/spend/images/video-game.jpg",
    username: "Video Game",
    price: 60,
  },
  {
    id: 8,
    profilePicture: "https://neal.fun/spend/images/amazon-echo.jpg",
    username: "Amazon Echo",
    price: 99,
  },
  {
    id: 9,
    profilePicture: "https://neal.fun/spend/images/year-of-netflix.jpg",
    username: "Year of Netflix",
    price: 100,
  },
  {
    id: 10,
    profilePicture: "https://neal.fun/spend/images/air-jordans.jpg",
    username: "Air Jordans",
    price: 125,
  },
  {
    id: 11,
    profilePicture: "https://neal.fun/spend/images/airpods.jpg",
    username: "Airpods",
    price: 199,
  },
  {
    id: 12,
    profilePicture: "https://neal.fun/spend/images/gaming-console.jpg",
    username: "Gaming Console",
    price: 299,
  },
  {
    id: 13,
    profilePicture: "https://neal.fun/spend/images/drone.jpg",
    username: "Drone",
    price: 350,
  },
  {
    id: 14,
    profilePicture: "https://neal.fun/spend/images/smartphone.jpg",
    username: "Smartphone",
    price: 699,
  },
  {
    id: 15,
    profilePicture: "https://neal.fun/spend/images/bike.jpg",
    username: "Bike",
    price: 800,
  },
  {
    id: 16,
    profilePicture: "https://neal.fun/spend/images/kitten.jpg",
    username: "Kitten",
    price: 1500,
  },
  {
    id: 17,
    profilePicture: "https://neal.fun/spend/images/puppy.jpg",
    username: "Puppy",
    price: 1500,
  },
  {
    id: 18,
    profilePicture: "https://neal.fun/spend/images/auto-rickshaw.jpg",
    username: "Auto Rickshaw",
    price: 2300,
  },
  {
    id: 19,
    profilePicture: "https://neal.fun/spend/images/horse.jpg",
    username: "Horse",
    price: 2500,
  },
  {
    id: 20,
    profilePicture: "https://neal.fun/spend/images/acre-of-farmland.jpg",
    username: "Acre of Farmland",
    price: 3000,
  },
  {
    id: 21,
    profilePicture: "https://neal.fun/spend/images/tesla.jpg",
    username: "Tesla",
    price: 75000,
  },
  {
    id: 22,
    profilePicture: "https://neal.fun/spend/images/single-family-home.jpg",
    username: "Single Family Home",
    price: 300000,
  },
  {
    id: 23,
    profilePicture: "https://neal.fun/spend/images/yacht.jpg",
    username: "Yatch",
    price: 7500000,
  },
  {
    id: 24,
    profilePicture: "https://neal.fun/spend/images/formula-1-car.jpg",
    username: "Formula 1 Car",
    price: 15000000,
  },
];
